In [67]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.svm import SVC
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [100]:
df = pd.read_csv("all_stocks_5yr.csv")
x = df.drop(['Name','volume'],axis='columns')
x[["year", "month", "day"]] = x["date"].str.split("-", expand = True)
# splitting the date on the basis of 
x = x.drop(['date'],axis='columns')
y = df['volume']
y = y/1000000
y = y.iloc[:6000]
x = x.iloc[:6000]
x.head(50)
# y.head()

     open   high    low  close  year month day
0   15.07  15.12  14.63  14.75  2013    02  08
1   14.89  15.01  14.26  14.46  2013    02  11
2   14.45  14.51  14.10  14.27  2013    02  12
3   14.30  14.94  14.25  14.66  2013    02  13
4   14.94  14.96  13.16  13.99  2013    02  14
5   13.93  14.61  13.93  14.50  2013    02  15
6   14.33  14.56  14.08  14.26  2013    02  19
7   14.17  14.26  13.15  13.33  2013    02  20
8   13.62  13.95  12.90  13.37  2013    02  21
9   13.57  13.60  13.21  13.57  2013    02  22
10  13.60  13.76  13.00  13.02  2013    02  25
11  13.14  13.42  12.70  13.26  2013    02  26
12  13.28  13.62  13.18  13.41  2013    02  27
13  13.49  13.63  13.39  13.43  2013    02  28
14  13.37  13.95  13.32  13.61  2013    03  01
15  13.50  14.07  13.47  13.90  2013    03  04
16  14.01  14.05  13.71  14.05  2013    03  05
17  14.52  14.68  14.25  14.57  2013    03  06
18  14.70  14.93  14.50  14.82  2013    03  07
19  14.99  15.20  14.84  14.92  2013    03  08
20  14.85  15.15  14.71  15.13  2013    03  11
21  15.14  15.60  14.95  15.50  2013    03  12
22  15.54  16.20  15.48  15.91  2013    03  13
23  15.98  16.36  15.93  16.25  2013    03  14
24  16.45  16.54  15.88  15.98  2013    03  15
25  15.80  16.33  15.71  16.29  2013    03  18
26  16.48  16.85  16.41  16.78  2013    03  19
27  17.13  17.33  16.87  17.23  2013    03  20
28  17.21  17.43  16.87  17.00  2013    03  21
29  17.10  17.29  16.77  16.86  2013    03  22
30  16.92  17.00  16.35  16.60  2013    03  25
31  16.67  16.84  16.50  16.51  2013    03  26
32  16.48  16.77  16.33  16.65  2013    03  27
33  17.00  17.09  16.82  16.97  2013    03  28
34  17.02  17.13  16.54  16.67  2013    04  01
35  16.48  16.50  15.71  15.74  2013    04  02
36  15.82  15.92  15.13  15.53  2013    04  03
37  15.12  15.71  15.12  15.69  2013    04  04
38  15.17  15.79  15.03  15.72  2013    04  05
39  15.82  15.97  15.53  15.84  2013    04  08
40  16.07  16.10  15.67  15.70  2013    04  09
41  15.74  15.98  15.70  15.78  2013    04  10
42  15.77  16.38  15.75  16.19  2013    04  11
43  16.11  16.39  15.95  16.14  2013    04  12
44  16.20  16.39  15.47  15.59  2013    04  15
45  15.96  16.74  15.81  16.37  2013    04  16
46  16.17  16.55  15.90  16.52  2013    04  17
47  16.54  16.54  15.95  16.10  2013    04  18
48  16.10  16.24  15.85  16.02  2013    04  19
49  15.99  16.00  15.50  15.52  2013    04  22

In [101]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
reg=linear_model.LinearRegression()
reg.fit(X_train, y_train)
X_train.shape

(4200, 7)

In [102]:
reg.coef_

array([ 0.7144289 ,  1.34079778, -1.84414299, -0.17893749, -3.56321577,
       -0.46928959,  0.04250149])

In [103]:
reg.intercept_

7192.463444720929

In [104]:
y_pred = reg.predict(X_test)
# y_test.shape

In [105]:
print('Mean squared error: %.2f'
      % mean_squared_error(y_test, y_pred))

Mean squared error: 648.31